name: Docker Image CI

on:
  push:
    # Publish 1.0.0 as Docker latest image.
    branches: [ 1.0.0 ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    # Логинемся на Docker Hub, DOCKERHUBPLATFORMBACKEND созданный ключ в settings secret, stdin - значит ввод
    - name: Log into registry
      run: echo "${{ secrets.DOCKERHUBPLATFORMBACKEND }}" | docker login -u ksergey1999 --password-stdin
    
    # Создаем docker compose из 2 сервисов благодаря чему получаем 2 images, которые далее сможем отправить на docker hub.
    - name: Build docker-compose
      run: |  
            docker volume create --name=myData
            docker-compose --file docker-compose.yml build
            docker-compose --file docker-compose.yml up -d
   
    # 1. Мы отмечаем локальный image как image принадлежащий к репозиторию ksergey1999/platform-backend под именем  database
    - name: Publish database
      run: |
          docker tag platform-backend_database ksergey1999/platform-backend:database
          docker push ksergey1999/platform-backend:database
    
    # 1. Мы отмечаем локальный image как image принадлежащий к репозиторию ksergey1999/platform-backend  под именем endpoint
    - name: Publish endpoint
      run: |
             docker tag platform-backend_endpoint ksergey1999/platform-backend:endpoint
             docker push ksergey1999/platform-backend:endpoint
